#!/bin/sh

wget https://dl.dropbox.com/u/1035515/mediumTest.out.bz2
wget https://dl.dropbox.com/u/1035515/smallTest.out.bz2

wget https://dl.dropbox.com/u/1035515/largeTest.in.bz2
wget https://dl.dropbox.com/u/1035515/mediumTest.in.bz2
wget https://dl.dropbox.com/u/1035515/smallTest.in.bz2

bzip2 -d mediumTest.out.bz2
bzip2 -d smallTest.out.bz2

bzip2 -d largeTest.in.bz2
bzip2 -d mediumTest.in.bz2
bzip2 -d smallTest.in.bz2
